### ISSUE TITLE
install-ko.bat 파일 인코딩 문제

### ISSUE THREAD

**Issue by affogatoman** [HelloWorld017/subtitle-renamer#1]
프로그램 자체는 손색없이 좋은데, 파일이 UTF-8로 인코딩 되어 있어서 오른쪽 클릭 시 나오는 메뉴에서 자막 이름 바꾸기 메뉴가 깨져 있더라고요 ㅎㅎ ANSI로 인코딩된 파일로 교체하면 해결될 듯 합니다.

**Comment by HelloWorld017** [comment]
제보해주셔서 감사합니다!

**Comment by caldosa2** [comment]
잘쓰고 있는데 자막파일 끝에 .ko가 붙게 하나 만들어주시면 감사하겠습니다. plex에 쓸때 필요합니다^^
